version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: hasura-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tasksdb
    ports:
      - "5433:5432"
    networks:
      - hasura-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.40.1
    restart: always
    container_name: hasura-engine
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/tasksdb
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: mysecret
    networks:
      - hasura-net

  backend-service:
    build:
      context: ./backend-node
    container_name: backend-service
    restart: "no"
    depends_on:
      - hasura
    environment:
      HASURA_URL: http://hasura:8080/v1/graphql
      HASURA_ADMIN_SECRET: mysecret
    networks:
      - hasura-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    restart: always
    depends_on:
      - backend-service
    ports:
      - "3200:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend-service:3001
      NEXT_PUBLIC_GRAPHQL_URL: http://hasura:8080/v1/graphql
    networks:
      - hasura-net

volumes:
  postgres_data:

networks:
  hasura-net:
